### ISSUE TITLE
Could not find play-services-basement.aar

### ISSUE THREAD

**Issue by bjtaylor1** [googlearchive/android-Notifications#7]
I get the following error when trying to compile this:

Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

**Comment by andrea-rosa** [comment]
I've found a workaround. According to [this](https://stackoverflow.com/a/52992754/7567483) answer on stackoverflow you have to change the following block:
```
allprojects {
    repositories {
        jcenter()
        google()
    }
}
```
with this 
```
allprojects {
    repositories {
        google()
        jcenter()
    }
}
```
in these files:
`Application/build.gradle`  
`Shared/build.gradle`  
`Wearable/build.gradle`  

And also change `.setVisibility(Notification.VISIBILITY_PUBLIC)` with `.setVisibility(NotificationCompat.VISIBILITY_PUBLIC)` at line 201 of `Application/src/main/java/com/example/android/wearable/wear/wearnotifications/handlers/BigTextIntentService.java`

**Comment by codingjeremy** [comment]
This should be fixed in the new migrated version at 
https://github.com/android/user-interface-samples

Please reopen there if it is not, and I will take a look. Thanks!
